/**
 * stretchLibrary.js — the built-in stretch catalogue.
 *
 * Lives here, not in the Stretches page, because two things need it: the page
 * (which merges it over the Exercise DB so there is always content) and
 * /ContentAudit (which reports the entries that have no database row, and so can
 * never be given a photo or a video).
 *
 * These records intentionally carry no image_url or youtube_url — they are text
 * only. Anything in here that is NOT also an Exercise record is, by definition,
 * a stretch a user can open with no photo and no video available.
 */

export const STRETCH_LIBRARY = [
  { id: "lib-arm-circle", name: "Arm Circle", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Full shoulder rotation warm-up. Muscles: Shoulders, Rotator Cuff. Cues: Make large circles, raise arm fully overhead each revolution.", instructions: ["Make large circles", "Raise arm fully overhead each revolution"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-hip-circle", name: "Hip Circle", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Standing hip rotation. Muscles: Hip Flexors, Glutes. Cues: Full circular motion, keep feet planted, rotate both directions.", instructions: ["Full circular motion", "Keep feet planted", "Rotate both directions"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-cat-cow", name: "Cat-Cow", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Spinal flexion and extension on all fours. Muscles: Spine, Core. Cues: Exhale arch (cat), inhale sag (cow), slow and controlled.", instructions: ["Exhale arch (cat)", "Inhale sag (cow)", "Slow and controlled"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-quad-stretch", name: "Quad Stretch", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Standing quad and hip flexor stretch. Muscles: Quadriceps, Hip Flexors. Cues: Pull foot to glute, keep knees together, stand tall.", instructions: ["Pull foot to glute", "Keep knees together", "Stand tall"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-toe-touch", name: "Toe Touch", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Standing hamstring stretch. Muscles: Hamstrings, Lower Back. Cues: Straight legs, reach for toes, slow stretch.", instructions: ["Straight legs", "Reach for toes", "Slow stretch"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-calf-stretch-wall", name: "Calf Stretch (wall)", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Wall-supported calf and Achilles stretch. Muscles: Calves, Achilles. Cues: Back leg straight with heel pressed down, lean into the wall, hold without bouncing.", instructions: ["Back leg straight with heel pressed down", "Lean into the wall", "Hold without bouncing"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-it-band-stretch", name: "IT Band Stretch", category: "mobility", difficulty: "intermediate", metric: "time", target_time: 30, description: "Standing or seated outer-thigh and IT band stretch. Muscles: IT Band, Outer Hip, Glutes. Cues: Cross one leg in front of the other, lean gently to the side, hold without bouncing.", instructions: ["Cross one leg in front of the other", "Lean gently to the side", "Hold without bouncing"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-thread-the-needle", name: "Thread the Needle", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Spinal rotation stretch from a quadruped position. Muscles: Upper Back, Shoulders, Spine. Cues: Thread one arm under the body, rest the shoulder and head on the floor, breathe into the stretch.", instructions: ["Thread one arm under the body", "Rest the shoulder and head on the floor", "Breathe into the stretch"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-seated-forward-fold", name: "Seated Forward Fold", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Seated hamstring and lower back stretch. Muscles: Hamstrings, Lower Back. Cues: Hinge at the hips with a long spine, reach toward the toes, avoid rounding the lower back forcefully.", instructions: ["Hinge at the hips with a long spine", "Reach toward the toes", "Avoid rounding the lower back forcefully"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-overhead-lat-stretch", name: "Overhead Lat Stretch", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Standing lat and side-body stretch. Muscles: Lats, Obliques, Shoulders. Cues: Reach one arm overhead and lean to the opposite side, keep the hips square and facing forward.", instructions: ["Reach one arm overhead and lean to the opposite side", "Keep the hips square and facing forward"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-overhead-tricep-stretch", name: "Overhead Tricep Stretch", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Standing tricep and shoulder stretch. Muscles: Triceps, Shoulders. Cues: Bend one elbow overhead, gently pull the elbow with the opposite hand, keep the chest lifted.", instructions: ["Bend one elbow overhead", "Gently pull the elbow with the opposite hand", "Keep the chest lifted"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-knees-to-chest", name: "Knees to Chest", category: "mobility", difficulty: "beginner", metric: "time", target_time: 30, description: "Supine lower-back release stretch. Muscles: Lower Back, Glutes, Hips. Cues: Pull both knees toward the chest, relax the shoulders flat on the floor, breathe slowly.", instructions: ["Pull both knees toward the chest", "Relax the shoulders flat on the floor", "Breathe slowly"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-forearm-stretch", name: "Forearm Stretch", category: "mobility", difficulty: "beginner", metric: "time", target_time: 20, description: "Wrist and forearm flexor/extensor stretch. Muscles: Forearms, Wrists. Cues: Extend the arm with palm up, gently pull the fingers back toward the body, then flip the hand over for the top-of-forearm stretch.", instructions: ["Extend the arm with palm up", "Gently pull the fingers back toward the body", "Then flip the hand over for the top-of-forearm stretch"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-standing-hamstring-stretch", name: "Standing Hamstring Stretch", category: "lower_body", difficulty: "beginner", metric: "time", target_time: 30, description: "Standing forward reach targeting the hamstrings. Muscles: Hamstrings, Calves. Cues: Slight knee bend, hinge at the hips, reach toward the toes, keep the back straight.", instructions: ["Slight knee bend", "Hinge at the hips", "Reach toward the toes", "Keep the back straight"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-hip-flexor-lunge-stretch", name: "Hip Flexor Lunge Stretch", category: "lower_body", difficulty: "beginner", metric: "time", target_time: 30, description: "Kneeling lunge stretch for the front hip. Muscles: Hip Flexors, Quadriceps. Cues: Back knee down, push the hips forward gently, keep the torso upright.", instructions: ["Back knee down", "Push the hips forward gently", "Keep the torso upright"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-seated-butterfly-stretch", name: "Seated Butterfly Stretch", category: "lower_body", difficulty: "beginner", metric: "time", target_time: 30, description: "Seated inner-thigh stretch with soles of the feet together. Muscles: Inner Thighs, Hips. Cues: Sit tall, let the knees drop toward the floor, gently press the knees down for more stretch.", instructions: ["Sit tall", "Let the knees drop toward the floor", "Gently press the knees down for more stretch"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-chest-opener-stretch", name: "Chest Opener Stretch", category: "upper_body", difficulty: "beginner", metric: "time", target_time: 20, description: "Standing chest and shoulder opener with hands clasped behind the back. Muscles: Chest, Shoulders. Cues: Clasp hands behind the back, lift the chest, draw the shoulder blades together.", instructions: ["Clasp hands behind the back", "Lift the chest", "Draw the shoulder blades together"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-neck-side-stretch", name: "Neck Side Stretch", category: "upper_body", difficulty: "beginner", metric: "time", target_time: 20, description: "Lateral neck stretch for tension relief. Muscles: Neck, Upper Traps. Cues: Tilt the head gently to one side, use the hand for light overpressure, keep the shoulders relaxed.", instructions: ["Tilt the head gently to one side", "Use the hand for light overpressure", "Keep the shoulders relaxed"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-child-s-pose", name: "Child's Pose", category: "full_body", difficulty: "beginner", metric: "time", target_time: 45, description: "Kneeling forward fold stretching the back and shoulders. Muscles: Lower Back, Lats, Hips. Cues: Sit the hips back toward the heels, reach the arms forward, relax the head down.", instructions: ["Sit the hips back toward the heels", "Reach the arms forward", "Relax the head down"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-pigeon-pose", name: "Pigeon Pose", category: "lower_body", difficulty: "intermediate", metric: "time", target_time: 45, description: "Deep hip and glute opener. Muscles: Glutes, Hip Rotators. Cues: Front shin angled forward, back leg extended straight, square the hips, fold forward gently.", instructions: ["Front shin angled forward", "Back leg extended straight", "Square the hips", "Fold forward gently"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-world-s-greatest-stretch", name: "World's Greatest Stretch", category: "full_body", difficulty: "intermediate", metric: "time", target_time: 30, description: "Dynamic multi-plane lunge and rotation stretch. Muscles: Hips, Hamstrings, Spine, Shoulders. Cues: Step into a lunge, drop the back hand down, rotate the opposite arm toward the ceiling, move smoothly between positions.", instructions: ["Step into a lunge", "Drop the back hand down", "Rotate the opposite arm toward the ceiling", "Move smoothly between positions"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-downward-dog", name: "Downward Dog", category: "full_body", difficulty: "intermediate", metric: "time", target_time: 40, description: "Inverted V stretch for the posterior chain. Muscles: Hamstrings, Calves, Shoulders, Back. Cues: Press the hips up and back, straighten the legs as much as comfortable, press through the hands.", instructions: ["Press the hips up and back", "Straighten the legs as much as comfortable", "Press through the hands"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-seated-spinal-twist", name: "Seated Spinal Twist", category: "core", difficulty: "intermediate", metric: "time", target_time: 30, description: "Seated rotational stretch for the spine and obliques. Muscles: Spine, Obliques, Lower Back. Cues: Sit tall, rotate the torso toward the back leg, use the arm for gentle leverage, keep the hips square.", instructions: ["Sit tall", "Rotate the torso toward the back leg", "Use the arm for gentle leverage", "Keep the hips square"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-figure-4-glute-stretch", name: "Figure-4 Glute Stretch", category: "lower_body", difficulty: "intermediate", metric: "time", target_time: 40, description: "Supine or seated glute and piriformis stretch. Muscles: Glutes, Piriformis, Hips. Cues: Cross one ankle over the opposite knee, gently pull the thigh toward the chest, keep the crossed foot flexed.", instructions: ["Cross one ankle over the opposite knee", "Gently pull the thigh toward the chest", "Keep the crossed foot flexed"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-doorway-chest-stretch", name: "Doorway Chest Stretch", category: "upper_body", difficulty: "intermediate", metric: "time", target_time: 30, description: "Chest and front-shoulder stretch using a doorway or wall. Muscles: Chest, Front Deltoids, Biceps. Cues: Forearm on the frame at shoulder height, gently rotate the body away, keep the elbow slightly below shoulder height.", instructions: ["Forearm on the frame at shoulder height", "Gently rotate the body away", "Keep the elbow slightly below shoulder height"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-cobra-stretch", name: "Cobra Stretch", category: "core", difficulty: "advanced", metric: "time", target_time: 60, description: "Prone backbend opening the front body. Muscles: Abs, Lower Back, Hip Flexors. Cues: Press through the hands, lift the chest while keeping the hips down, ease into the range without forcing.", instructions: ["Press through the hands", "Lift the chest while keeping the hips down", "Ease into the range without forcing"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-supine-spinal-twist", name: "Supine Spinal Twist", category: "core", difficulty: "advanced", metric: "time", target_time: 60, description: "Lying rotational stretch for the spine and glutes. Muscles: Spine, Glutes, Obliques. Cues: Lie on the back, drop both knees to one side, keep the shoulders flat on the floor, breathe into the stretch.", instructions: ["Lie on the back", "Drop both knees to one side", "Keep the shoulders flat on the floor", "Breathe into the stretch"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-standing-quadriceps-stretch", name: "Standing Quadriceps Stretch", category: "lower_body", difficulty: "advanced", metric: "time", target_time: 45, description: "Standing front-thigh stretch. Muscles: Quadriceps, Hip Flexors. Cues: Pull the heel toward the glutes, keep the knees together, stand tall and use support if needed.", instructions: ["Pull the heel toward the glutes", "Keep the knees together", "Stand tall and use support if needed"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
  { id: "lib-shoulder-cross-body-stretch", name: "Shoulder Cross-Body Stretch", category: "upper_body", difficulty: "advanced", metric: "time", target_time: 45, description: "Cross-body stretch for the rear shoulder. Muscles: Rear Deltoids, Upper Back. Cues: Pull one arm across the chest, use the opposite arm for gentle pressure, keep the shoulder down away from the ear.", instructions: ["Pull one arm across the chest", "Use the opposite arm for gentle pressure", "Keep the shoulder down away from the ear"], tips: ["Move slowly into the stretch and breathe steadily — never bounce or jerk.", "Stretch to gentle tension, not pain. Ease off if anything feels sharp.", "Hold for the full time, then repeat on the other side if it is one-sided."], },
];
